In [1]:
import numpy as np

In [108]:

def make_matrix(i, size):
    pix = np.zeros((size, size))
    for row in range(0, size):
        for col in range(0, size):
            value = bool((i >> (row * size)) & (1 << col))
            pix[row, col] = value * 255
    return pix


def show_matrix(value, size):
    print(f'{value} {value:016b}')
    print(make_matrix(value, size))

def make_upscaling_pat(size=4):
    options = {}
    posibilities = 2 ** (size * size)
    for i in range(0, posibilities):
        pix = make_matrix(i, size)
        options[i] = (f'{i:016b}', pix)
        
    return options


In [112]:
make_upscaling_pat(4)[65535]

('1111111111111111',
 array([[255., 255., 255., 255.],
        [255., 255., 255., 255.],
        [255., 255., 255., 255.],
        [255., 255., 255., 255.]]))

In [111]:
a = make_upscaling_pat(3)
a[511]

512


('0000000111111111',
 array([[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]]))

In [101]:
make_upscaling_pat(2)[255]

('0000000011111111',
 array([[255., 255.],
        [255., 255.]]))

In [ ]:
    kernel = np.zeros((3, 3))
    
    kernel[1, 1] = 1
    kernel[0, 1] = 1
    kernel[1, 0] = 1
    kernel[1, 2] = 1
    kernel[2, 1] = 1
    kernel = kernel / 5 
    print(kernel)
    

In [142]:
import scipy

def expand(original, mid=128, high=255):
    w, h = original.shape
    pix = np.zeros((w * 2, w * 2))
    
    kernel = np.ones((2, 2))
    kernel[0, 0] = 1
    kernel[1, 0] = 1
    kernel[0, 1] = 1
    print(kernel)
    
    for r in range(w):
        for c in range(h):
            v = original[r, c]
            
            pix[r * 2 + 1, c * 2 + 1] = v / 2
            pix[r * 2 + 0, c * 2 + 0] = v / 2
            pix[r * 2 + 0, c * 2 + 1] = v * 0
            pix[r * 2 + 1, c * 2 + 0] = v 
    
    print(original)
    return pix

expand(make_upscaling_pat(2)[4][1])

[[1. 1.]
 [1. 1.]]
[[  0.   0.]
 [255.   0.]]


array([[  0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ],
       [127.5,   0. ,   0. ,   0. ],
       [255. , 127.5,   0. ,   0. ]])

In [149]:
expand(make_upscaling_pat(3)[4][1])

[[1. 1.]
 [1. 1.]]
[[  0.   0. 255.]
 [  0.   0.   0.]
 [  0.   0.   0.]]


array([[  0. ,   0. ,   0. ,   0. , 127.5,   0. ],
       [  0. ,   0. ,   0. ,   0. , 255. , 127.5],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ]])

In [92]:
show_matrix(65535)

65535 1111111111111111
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
print(len(options))

256


In [88]:
for i in range(4):
    print(f'{(1 << i):04b}')

0001
0010
0100
1000


In [28]:
i = 0b10000
print(f'{i >> 4:04b}')

0001
